### ISSUE TITLE
fatal error when exe executing  

### ISSUE THREAD

**Issue by yasharth291** [yasharth291/Crop-Warehouse-management-system#2]
so there is an fatal error after converting the python code into .exe file. when we are starting the .exe file it is showing fatal error but my code is working fine.

**Comment by yasharth291** [comment]
@brentvollebregt

**Comment by brentvollebregt** [comment]
Why have I been mentioned here? There is no context at all apart from a five-word title...

**Comment by yasharth291** [comment]
what do you need??

**Comment by yasharth291** [comment]
@brentvollebregt

**Comment by brentvollebregt** [comment]
Hello, I have been mentioned here for a second time. Again, what have I been mentioned here for?

**Comment by yasharth291** [comment]
i need your help. i read your similar comment on same error.

**Comment by brentvollebregt** [comment]
This issue has been created on a repo that I do not manage or contribute to. Are you talking about auto-py-to-exe? This repo is not auto-py-to-exe.

**Comment by yasharth291** [comment]
no you commented on someone else so you, you said it is because of third party setting or something else.
